### ISSUE TITLE
Add attribute to ignore props

### ISSUE THREAD

**Issue by maranmaran** [IowaComputerGurus/netcore.utilities.spreadsheet#21]
This would be handy

Starred

**Comment by mitchelsellers** [comment]
@maranmaran I'll look at this ASAP, should be pretty simple addition

**Comment by mitchelsellers** [comment]
Implementation of this would be similar to that of the ColumnFormat attribute, if present on a property it would be ignored on export.  [Link to Example](https://github.com/IowaComputerGurus/netcore.utilities.spreadsheet/blob/develop/src/NetCore.Utilities.Spreadsheet/SpreadsheetColumnFormatAttribute.cs)
