### ISSUE TITLE
sheet name & skip many rows

### ISSUE THREAD

**Issue by ferdaousHar** [IowaComputerGurus/netcore.utilities.spreadsheet#26]
Hello @mitchelsellers and @msieker,

thank you for the nice library !
I need to call the method ParseDocument by specifying the name of the sheet instead of its number.
Also I need to skip some rows instead of just the header.
Would you please help me by adding these features to your library ?

Regards.

**Comment by mitchelsellers** [comment]
Sorry for the delayed response here, I assume this is for an import?  Is this correct?

**Comment by ferdaousHar** [comment]
Thank you for your reply.
Yes please, it is for the import...I need actually an overload for the method ParseDocument in the OpenXmlSpreadsheetParser class getting in parameter the sheetName and the number of rows to skip besides to the fileStream which is already there.

Best Regards.

**Comment by mitchelsellers** [comment]
Looking at this I think we could do something to support this without too much difficulty via a few additional methods that could be called from the parser.  

We are a bit backlogged at the moment, but I will see if I can get some time dedicated to this soon, as we work on OpenSource stuff as soon as practical.

**Comment by mitchelsellers** [comment]
@ferdaousHar We are pushing a release today that add the usability to import by sheet name
