### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0

### ISSUE THREAD

**Issue by JoacimWall** [IowaComputerGurus/netcore.utilities.spreadsheet#31]
Hi 
Using this nuget inside a visual studio extension for VS 2022 for Mac. 
I don't know if this is related to the nuget or the environment.  

//Thanks Joacim

**Comment by mitchelsellers** [comment]
What type of project is this in?  I'll try to recreate.

Is this a Preview version of VS or Standard

**Comment by JoacimWall** [comment]
Hi
I have trying in vs2022 standard and preview. 
it’s a addin (extension)

https://github.com/JoacimWall/Visual-studio-multilingual-extension/tree/main/src

the project named multilingualextension.Mac is the project that gets the error. If you debug that and open console app sample and right click a resx file you get a pop up menu for export to excel.  

Then you get the error. 
but I think the error is not in your code if I use your nuget in standard app it works. 

Regards Joacim

**Comment by mitchelsellers** [comment]
@JoacimWall It appears that this package should work - https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/

Did you try to add that NUGET to your project?

**Comment by mitchelsellers** [comment]
I have been unable to recreate this issue. if you are still having an issue let me know.
