### ISSUE TITLE
How are dates formatted when generating a spreadsheet?

### ISSUE THREAD

**Issue by kikaragyozov** [IowaComputerGurus/netcore.utilities.spreadsheet#42]
I'm trying to understand what date format dates use in the generated files.

Digging into the code, I noticed that NumberFormat of 22 is used whenever a DateTime object is encountered. Is that format locale-specific? I also noticed that there is another NumberFormat with an id of 300, which DateFormat is `mm/dd/yyyy`, but it's not used in my case and frankly I'm not sure when it would?

The file I generated uses the following Date format when opened with Excel - `m/d/yyyy h:mm` - is this what the date will always be formatted as? Or is it locale-specific?

I'd like to generate an Excel file, preferably specifying the date format to use for date fields and/or the format itself not being reliant on any specific culture/locale/OS configurations.

**EDIT:** Perhaps NumberFormat 300 is used when you apply `SpreadsheetColumn` attribute with `Format` value of `d`?

**I'm unable to parse back the generated file with other excel readers.** The date is always stored in the following fashion, even though when you open the file it's never stored like that: "2023-01-09T11:46:55.000". Opening the file in Excel and just saving it without modifying anything else, makes everything work, which is bizarre.

**Comment by mitchelsellers** [comment]
Sorry for the delayed response for this one, I was trying to dig into this a bit as well, as I'm not seeing any issues, but working to confirm.

This area sets some of the style usage - https://github.com/IowaComputerGurus/netcore.utilities.spreadsheet/blob/9abe9d9a68d9a9040cf2d9bc50916595a493e6ae/src/NetCore.Utilities.Spreadsheet/OpenXmlSpreadsheetGenerator.cs#L256

A date, with no customization should be using this style = https://github.com/IowaComputerGurus/netcore.utilities.spreadsheet/blob/9abe9d9a68d9a9040cf2d9bc50916595a493e6ae/src/NetCore.Utilities.Spreadsheet/OpenXmlSpreadsheetGenerator.cs#L384 - Which would use the `mm/dd/yyyy` pattern

The referenced code for NumberFormat of 22 appears to be unused and should be removed.

At the end of the day, I think we may need to explore a way to allow you to pass a full format string in, and create a custom number format on the fly

**Comment by mitchelsellers** [comment]
Correction - Date with no customization would be using 22.  If a format string of "d" is used then it should utilize  the custom one.

This explains with no attribute that it is a date/time.  This "may" be local specific as the format specifier is internal
