### ISSUE TITLE
Support for column name localization

### ISSUE THREAD

**Issue by Mitroz** [IowaComputerGurus/netcore.utilities.spreadsheet#55]
The attribute SpreadsheetColumnAttribute could contain the resource file type and a key to allow localizable column names.

**Comment by Mitroz** [comment]
Hi,
I have a complete implementation, but I can't create a branche for a pull request.

**Comment by mitchelsellers** [comment]
@Mitroz you should be able to from your fork contribute the element in a PR.

This tutorial from GitHub should help guide - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
