### ISSUE TITLE
The file generated on Linux corrupted 

### ISSUE THREAD

**Issue by wzhou-grid** [IowaComputerGurus/netcore.utilities.spreadsheet#62]
I am using .NET 6 and the library version is 7.2.0. The Excel file can be generated on both Windows and CentOS 7. However, the file generated on Linux cannot be opened. The error message is: 'We found a problem with some content in example.xlsx'.
Furthermore, the file size when generated on Linux is larger compared to when it is generated on Windows.

**Comment by mitchelsellers** [comment]
@wzhou-grid Any chance you can either post here, or email us a copy of different results?

**Comment by wzhou-grid** [comment]
Sorry, it was my bad.
The generated file on server is downloaded via an ajax call on the clients side. I forgot to add 
`xhrFields:{
        responseType: 'blob'
    },`
in the ajax. After adding the above codes, everything works fine.

**Comment by mitchelsellers** [comment]
Awesome, glad you got it working!
